language: ruby
rvm:
  - 2.0.0
env:
  global:
  - USER="Werwolf2303"
  - EMAIL="gianlucabeil@outlook.de"
  - REPO="werwolf2303.github.io"
  - FILES="README.md"
  - GH_REPO="github.com/werwolf2303/werwolf2303.github.io.git"
after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone git://${GH_REPO}
  - mv -f ${FILES} ${REPO}
  - cd ${REPO}
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add ${FILES}
  - git commit -m ${MESSAGE}
  - git push "https://${TRAVIS_SECURE_TOKEN_NAME}@${GH_REPO}" master > /dev/null 2>&1
