# This is a basic workflow to help you get started with Actions

name: Python package

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        working-directory: ./system
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install spotdl
        pip install setuptools wheel twine
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: SpotDL
      run:
        spotdl --song https://open.spotify.com/track/76nqCfJOcFFWBJN32PAksn?si=b4mUan6qTbmtCGx81UdvAQ
    - name: Upload1
      run: |
        git config --global user.name "WorkFlow"
    - name: Upload2
      run: |
        git config  user.email "gianlucabeil@outlook.de"
    - name: Upload3
      run: |
        git config user.name "gianlucabeil@outlook.de"
    - name: Upload4
      run: |
        git init
    - name: Upload5
      run: |
         git add "Ava Max - Kings & Queens.opus"
    - name: Upload6
      run: |
        git push -u origin master
        
       
        
        
        
        



      
        

        

